### ISSUE TITLE
?c / ?despawn

### ISSUE THREAD

**Issue by TheRealHomeland** [carsakiller/Carsas-CommandsV2#87]
### Suggested Name

?c or ?despawn

### Command Purpose

Allow players to remove their own vehicles through a ?c command or ?despawn. Would be helpful for players to have a ?vehicles command or something to see their spawned in vehicles & IDs to quick reference

### Which roles do you think should have access by default?

- [X] Admin
- [X] Moderator
- [X] Auth
- [X] Everyone

**Comment by carsakiller** [comment]
Hello 👋

There already exists a [`?clearVehicle`](https://c2.carsakiller.com/cc-website/docs/commands#clearVehicle) command that despawns vehicles given their ID. There is also [`?vehicleList`](https://c2.carsakiller.com/cc-website/docs/commands#vehicleList) to see a list of the spawned vehicles, and [`?vehicleIDs`](https://c2.carsakiller.com/cc-website/docs/commands#vehicleIDs) or `?vids` to see the IDs of vehicles near you in 3D space.

**Comment by TheRealHomeland** [comment]
> Hello 👋
> 
> There already exists a [`?clearVehicle`](https://c2.carsakiller.com/cc-website/docs/commands#clearVehicle) command that despawns vehicles given their ID. There is also [`?vehicleList`](https://c2.carsakiller.com/cc-website/docs/commands#vehicleList) to see a list of the spawned vehicles, and [`?vehicleIDs`](https://c2.carsakiller.com/cc-website/docs/commands#vehicleIDs) or `?vids` to see the IDs of vehicles near you in 3D space.

Apologies for reopening, just for clarification; is this a command that any users by default can use/will they only be able to clear their own spawned vehicles instead of any vehicle that they're near/have to ID to? Thank you!!

**Comment by carsakiller** [comment]
[`?clearVehicle`](https://c2.carsakiller.com/cc-website/docs/commands#clearVehicle) (or `?cv` for short) is intended to be used by moderators and admins so that they can remove the vehicles of others. Most people play in sandbox mode, meaning users can use the map to return and despawn their vehicles, so there was never much of a need for your use case.

That being said, I can see how it would be useful to have a command that allows users to only despawn *their* vehicles. To implement this, we would probably add a new command, as the permissions are easier to handle that way. Then we could have `?cv` for moderators where all vehicles can be removed, and the new command where only that user's vehicles can be removed.  If you'd like this to be added, please create a new issue for it.
